config/routes.rb
Rails.application.routes.draw do

  match "/report_back", :to => "reports#lolcat", :via => [:get]
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  namespace :admin do
    resources :blog_rss_feeds
  end

  get "/rss-feeds" =>"home#rss_feeds"
  get "/rss/category/:id" => "home#get_rss_feed_of_category"
  get "/rss/publisher/:id" => "home#get_rss_feed_of_publisher"
  get "/rss/countries/:id" => "home#get_rss_feed_of_country"
  get "/rss/continents/:id" => "home#get_rss_feed_of_continents"
  get "/rss/regions/:id" => "home#get_rss_feed_of_regions"
  get "/rss/news-and-update" => "home#get_rss_feed_of_news_and_update"
  get "/rss/latest-reports" => "home#get_latest_reports"
  get "/rss/top-selling-reports" => "home#get_top_selling_reports"
  get "/rss/upcoming-reports" => "home#get_rss_feed_of_upcoming_reports"
  get "/rss/popular-categories" => "home#get_rss_feed_of_popular_categories"
  post "/show_side_panel_of_category" => "home#show_side_panel_of_category"

  post "/show_all_publishers" => "report_filters#show_all_publishers"
  post "/show_default_publishers" => "report_filters#show_default_publishers"
  post "/show_filter_reports" => "report_filters#show_filter_reports"
  get "/get_all_publishers" => "report_filters#get_all_publishers"
  get "/sort_publishers/:name" =>"report_filters#sort_publishers"
  post "/show_all_countries" => "report_filters#show_all_countries"
  post "/show_all_categories" => "report_filters#show_all_categories" 
  post "/show_all_continents" => "report_filters#show_all_continents"
  post "/show_all_regions" => "report_filters#show_all_regions"
  post "/show_selected_regions" => "report_filters#show_selected_regions"
  post "/show_selected_continents" => "report_filters#show_selected_continents"
  post "/reset_to_default_by_category" => "categories#reset_to_default_by_category"
  post "/new_report_enquiry" => "home#new_report_enquiry"
  post "/hdfc_secret" => "shopping_carts#hdfc_secret"
  post "/user_detail" => "shopping_carts#user_detail"

  get "/reset_countries" => "report_filters#reset_countries"
  post "/advance_search_countries" => "report_filters#advance_search_countries"
  
  resources :blogs, only: [:show,:index] do
    get 'blog_comments'
    collection do
      match "/category/:slug", :to => "blogs#blog_category",  :via => [:get, :post], :as => :blog_category
      match 'search' => 'blogs#search', :via => [:get, :post], :as => :blog_search
    end
  end
  get 'tags/:tag', to: 'blogs#index', as: :tag

  
  match 'blogs/by_year_and_month/:year/:month' => 'blogs#by_year_and_month', :via => [:get, :post], :as=> :blogs_by_year_and_month

  
  resources :user_sessions, only: [:new,:create,:destroy]
  
  post "/transaction/buynowccavRequestHandler" => "shopping_carts#buynowccavRequestHandler"
  match "/transaction/ccavRequestHandler" =>'shopping_carts#ccavRequestHandler', :via => [:get, :post]

  match "/transaction/ccavResponseHandler" =>'shopping_carts#ccavResponseHandler', :via => [:get, :post]
  match "/transaction/buynowCcavenueResponse" =>'shopping_carts#buynowCcavenueResponse', :via => [:get, :post]

  match "/transaction/cancel" =>'shopping_carts#cancel_transaction', :via => [:get, :post]
  resources :users, only: [:show,:new,:create]
  get 'signup' => 'users#new', :as => :signup

  root :to => 'home#index'

  get 'login'   => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout
  get 'signout' => 'user_sessions#destroy', as: :signout
  resources :password_resets, :only => [:new, :edit, :update]
  resources :news_updates, :only => [:show,:index], :path => '/press-release'
  namespace :admin do 
    resources :blogs do
      collection do
        get "blog_logs"
        get "blog_log_detail"
      end
    end
    match '/dashboard' => "dashboard#index", :via => ["get"], :as => :root
    match "/blogs/:id/delete", :to => "blogs#destroy", :via => ["delete"]
    match "/blog_rss_feeds/:id/delete", :to => "blog_rss_feeds#destroy", :via => ["delete"]
    resources :categories
    match "/categories/:id/delete", :to => "categories#destroy", :via => ["delete"]
    resources :publishers
    match "/publishers/:id/delete", :to => "publishers#destroy", :via => ["delete"]
    resources :pages
    resources :news_updates
    match "/news_updates/:id/delete", :to => "news_updates#destroy", :via => ["delete"]
    resources :reports do
      collection do
        match 'search' => 'reports#search', :via => [:get], :as => :search
        match 'search_reports' => 'reports#search_reports', :via => [:post]
        post :edit_multiple
        put :update_multiple
        post :upload_multiple
        post :save_position
        post :update_sheet
      end 

    end

    match "report_labels" =>'reports#report_labels', :via => [:get, :post]
    match "deactive_reports" =>'reports#deactive_reports', :via => [:get, :post]
    match "upload_files" => 'reports#upload_files', :via => [:get, :post]
    match "sort_reports" =>'reports#sort_reports', :via => [:get, :post]
   

    match "/reports/:id/delete", :to => "reports#destroy", :via => ["delete"]
    resources :messengers
    resources :conversations, only: [:show,:create] do
       resources :messengers
    end
    resources :orders
    resources :subscribers, :only => [:index, :show]  do 
      collection do
        post :toggle_active
      end
    end
    resources :testimonials
    match "/testimonials/:id/delete", :to => "testimonials#destroy", :via => ["delete"]
    match "/newsletter_templates/:id/delete", :to => "newsletter_templates#destroy", :via => ["delete"]
    match "/subscribers/:id/delete", :to => "subscribers#destroy", :via => ["delete"]
    match "order_details" =>'orders#order_details', :via => [:get, :post]
    resources :enquiries do
      collection do
        match 'list'=>"enquiries#list" ,:via=>[:get,:post]
        match 'list/:date'=>"enquiries#list_by_date" ,:via=>[:get,:post]
        match 'list/:date'=>"enquiries#delete_list" ,:via=>[:get,:delete]
        post :edit_multiple
      end
    end
   
    match "/pages/:id/delete", :to => "pages#destroy", :via => ["delete"]
    match "/enquiries/:id/delete_contact_us", :to => "enquiries#delete_contact_us", :via => ["delete"]
    
    match "/enquiries/:id/delete", :to => "enquiries#destroy", :via => ["delete"]
    match "contact_us" =>'enquiries#contact_us', :via => [:get, :post]
    match "/admin_change_password" => "dashboard#change_password", :via => [:get, :post]

    resources :newsletter_templates do 
      collection do
        post :send_multiple
        post :delete_multiple
      end
    end

    resources :clients
    match "/clients/:id/delete", :to => "clients#destroy", :via => ["delete"]
  end

  match "/send_password" => "password_resets#send_password" , :via=>[:post]
  match "/update_password" => "password_resets#update" , via: [:patch]
  match "/upload_excelsheet" => "admin/reports#upload_multiple" , via: [:post]
  match "/upload_reports" => "admin/reports#upload_reports" , via: [:post,:get]

  match "/upload_update_reports" => "admin/reports#upload_update_reports" , via: [:post,:get]

  resources :reports, only: [:show,:index]  do
    collection do
       match 'search' => 'reports#search', :via => [:get, :post], :as => :search
       get :get_all_reports
       get 'currency_section'
       post :show_advanced_search
    end 
    get :reset_filterrific, on: :collection    
  end 
  match "/reports/:id/:slug", :to => "reports#show", :via => ["get"]

  resources :categories, only: [:show,:index]

  resources :regions, only: [:show,:index] do
    member do
      match "/country_wise/:country_id", :to => "regions#country_wise", :via => ["get"]
    end
    collection do
      get 'reset_filter'
    end
  end
  resources :publishers, only: [:show,:index] do 
    collection do
      get 'load_more_publisher'
    end
  end
  resources :messages, only: [:create]
  resource :shopping_cart, only: [:show,:create]
  resources :pages, :only => [:show]
  match "/remove_item" => 'shopping_carts#remove_item', :via => [:get, :post]
  post "reports/enquiry" => "reports#enquiry"
  post "reports/enquiry_link" => "reports#enquiry_link"

  get "/clear_cart" => 'shopping_carts#clear_cart'
  get "/load_add_to_cart" => "shopping_carts#load_add_to_cart"
  get "/load_place_order_items" => "shopping_carts#load_place_order_items"

  post "/add_to_cart" => "shopping_carts#add_to_cart"
  

  post "blogs/post_comment" => "blogs#post_comment"

  get "/manage_address"  => 'shopping_carts#manage_address'
  get "/checkout"  => 'shopping_carts#checkout'
  get "/place_order"=> 'shopping_carts#place_order'
  get "/paypal_order_cancel"=> 'shopping_carts#paypal_order_cancel'
  get "/buynow_paypal_cancel"=> 'shopping_carts#buynow_paypal_cancel'
  resources :customers
  match "/update_quantity" => "shopping_carts#update_quantity", via: "post"
  match "/update_user" => "users#update_user", via: "post"
  match "/change_password" => "users#change_password", :via => [:get, :post]
  match "/update_password" => "users#update_password", :via => [:get, :post]
  match "/create_user" => "shopping_carts#create_user", via: "post"
  match "/signin_user" => "shopping_carts#signin_user", via: "post"
  match "/create_customer" => "shopping_carts#create_customer", via: "post"
  match "/complete_order" => "orders#complete_order", via: "post"
  match "/complete_ccavenue_order" => "orders#complete_ccavenue_order", :via => [:get, :post]

  match "/ccavenue_transfer" => "orders#ccavenue_transfer" , via: "post"
  match "/new_user_ccavenue_transfer" => "orders#new_user_ccavenue_transfer" , via: "post"
  
  match "/buynow_ccavenue_transfer" => "orders#buynow_ccavenue_transfer" , via: "post"

  get "purchase_complete" => "orders#purchase_complete"
  get "purchase_cancel" => "orders#purchase_cancel"
  
  get "checkout_complete" => "orders#checkout_complete"
  
  match "/express_checkout" => "orders#express_checkout", via: "post"

app/models/admin/blog_rss_feed.rb
class Admin::BlogRssFeed < ActiveRecord::Base
  self.table_name = "admin_blog_rss_feeds"
end

app/controllers/admin/blog_rss_feeds_controller.rb
class Admin::BlogRssFeedsController < Admin::BaseController
  before_action :set_admin_blog_rss_feed, only: [:show, :edit, :update, :destroy]

  # GET /admin/blog_rss_feeds
  # GET /admin/blog_rss_feeds.json
  def index
    @admin_blog_rss_feeds = Admin::BlogRssFeed.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /admin/blog_rss_feeds/1
  # GET /admin/blog_rss_feeds/1.json
  def show
  end

  # GET /admin/blog_rss_feeds/new
  def new
    @admin_blog_rss_feed = Admin::BlogRssFeed.new
  end

  # GET /admin/blog_rss_feeds/1/edit
  def edit
  end

  # POST /admin/blog_rss_feeds
  # POST /admin/blog_rss_feeds.json
  def create
    @admin_blog_rss_feed = Admin::BlogRssFeed.new(admin_blog_rss_feed_params)

    respond_to do |format|
      if @admin_blog_rss_feed.save
        format.html { redirect_to admin_blog_rss_feeds_path, notice: 'Blog rss feed was successfully created.' }
        format.json { render :show, status: :created, location: @admin_blog_rss_feed }
      else
        format.html { render :new }
        format.json { render json: @admin_blog_rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/blog_rss_feeds/1
  # PATCH/PUT /admin/blog_rss_feeds/1.json
  def update
    respond_to do |format|
      if @admin_blog_rss_feed.update(admin_blog_rss_feed_params)
        format.html { redirect_to admin_blog_rss_feeds_path, notice: 'Blog rss feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_blog_rss_feed }
      else
        format.html { render :edit }
        format.json { render json: @admin_blog_rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/blog_rss_feeds/1
  # DELETE /admin/blog_rss_feeds/1.json
  def destroy
    @admin_blog_rss_feed.destroy
    respond_to do |format|
      format.html { redirect_to admin_blog_rss_feeds_url, notice: 'Blog rss feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_blog_rss_feed
      @admin_blog_rss_feed = Admin::BlogRssFeed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_blog_rss_feed_params
      params.require(:admin_blog_rss_feed).permit(:url, :title, :number_of_feeds)
    end
end

app/views/admin/blog_rss_feeds/_form.html.erb
<%= form_for @admin_blog_rss_feed,:html => { :multipart => true , :class=>"form-horizontal"} do |f| %>
    <div class="form-group">
      <label class="col-lg-2 control-label">Title</label>
      <div class="col-lg-5">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-2 control-label">URL</label>
      <div class="col-lg-5">
        <%= f.text_field :url, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label">Category</label>
      <div class="col-lg-5">
 
     <%= f.select :number_of_feeds, options_for_select(1..20), { prompt: "select number" } ,:class=>"form-control" %>
      </div>
    </div>




    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-6">
        <button type="submit" class="btn btn-sm btn-success">
          Save
        </button>
        <button type="button" onclick="javascript:history.back()", class="btn btn-sm btn-default">
          Back
        </button>
      </div>
    </div>

                <% end %>

app/views/admin/blog_rss_feeds/edit.html.erb
<%= render "admin/shared/left_menu"%>
<div class="mainbar">

	<!-- Page heading -->
	<div class="page-head">
		<h2 class="pull-left"><i class="fa fa-file-o"></i> Blogs</h2>

		<!-- Breadcrumb -->
		<div class="bread-crumb pull-right">
			<a href="/admin/dashboard"><i class="fa fa-home"></i> Home</a>
			<!-- Divider -->
			<span class="divider">/</span>
			<a href="/admin/blog_rss_feeds" class="">Blog Rss Feed</a>
			<span class="divider">/</span>
			Edit
		</div>

		<div class="clearfix"></div>

	</div>
	<!-- Page heading ends -->

	<!-- Matter -->
	<div class="matter">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="widget">
						<div class="widget-head">
							<div class="pull-left">
								Edit Blog Rss Feed
							</div>
						
							<div class="clearfix"></div>
						</div>
						<div class="widget-content">
							<div class="padd">
								<br/>
								<%= render 'form' %>
								

							</div>
						</div>
						<div class="widget-foot">

							<div class="clearfix"></div>

						</div>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/admin/blog_rss_feeds/index.html.erb
<%= render "admin/shared/left_menu"%>
<div class="mainbar">

  <!-- Page heading -->
  <div class="page-head">
    <h2 class="pull-left"><i class="fa fa-file-o"></i> Blogs</h2>

    <!-- Breadcrumb -->
    <div class="bread-crumb pull-right">
      <a href="/admin/dashboard"><i class="fa fa-home"></i> Home</a>
      <!-- Divider -->
      <span class="divider">/</span>
      Blogs
    </div>

    <div class="clearfix"></div>

  </div>
  <!-- Page heading ends -->

  <!-- Matter -->

  <div class="matter">
    <div class="container">
      <div class="row">
        <div class="col-md-12">

          <div class="widget">
            <div class="widget-head">
              <div class="pull-left">
                Blogs
              </div>
              
              <div class="clearfix"></div>
            </div>

            <%#= @category.nil? ? 'Main categories' : @category.name %>
            <table class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                
                  <th>Title</th>
                  <th>Rss feed url</th>
                   <th>Number of feeds</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                    <% @admin_blog_rss_feeds.each do |admin_blog_rss_feed| %>
                <tr>
                    <td><%= admin_blog_rss_feed.title %></td>
                   <td>  <%= admin_blog_rss_feed.url%></td>
                    <td>  <%= admin_blog_rss_feed.number_of_feeds%></td>
                  <td>
                  <%if current_user.is_superadmin || current_user.is_blog_admin %>
                   <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_blog_rss_feed_path(admin_blog_rss_feed) , :class=>'btn btn-xs btn-warning'  %> <a href="/admin/blog_rss_feeds/<%= admin_blog_rss_feed.id %>/delete" data-confirm="Are you sure?" data-method="delete" class="btn btn-xs btn-danger" ><i class="fa fa-times"></i> </a>
                  <%end%>
                 </td>
                </tr>
                <% end %>

              </tbody>
            </table>

            <div class="widget-foot">
          
              <div class="pull-left">
                <%= link_to  "New Blog rss feed", new_admin_blog_rss_feed_path, :class => 'btn btn-sm btn-primary' %>
              </div>

              <div class="pull-right">
                <%= will_paginate @admin_blog_rss_feeds, renderer: BootstrapPagination::Rails %>

              </div>

              <div class="clearfix"></div>

            </div>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/blog_rss_feeds/new.html.erb
<%= render "admin/shared/left_menu"%>
<div class="mainbar">

	<!-- Page heading -->
	<div class="page-head">
		<h2 class="pull-left"><i class="fa fa-file-o"></i> Blogs</h2>

		<!-- Breadcrumb -->
		<div class="bread-crumb pull-right">
			<a href="/admin/dashboard"><i class="fa fa-home"></i> Home</a>
			<!-- Divider -->
			<span class="divider">/</span>
			<a href="/admin/blog_rss_feeds" class="">Blog Rss Feed</a>
			<span class="divider">/</span>
			New
		</div>

		<div class="clearfix"></div>

	</div>
	<!-- Page heading ends -->

	<!-- Matter -->
	<div class="matter">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="widget">
						<div class="widget-head">
							<div class="pull-left">
								New Blog Rss Feed
							</div>
						
							<div class="clearfix"></div>
						</div>
						<div class="widget-content">
							<div class="padd">
								<br/>
								<%= render 'form' %>
								

							</div>
						</div>
						<div class="widget-foot">

							<div class="clearfix"></div>

						</div>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/admin/blog_rss_feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @admin_blog_rss_feed.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @admin_blog_rss_feed.title %>
</p>

<p>
  <strong>Number of feeds:</strong>
  <%= @admin_blog_rss_feed.number_of_feeds %>
</p>

<%= link_to 'Edit', edit_admin_blog_rss_feed_path(@admin_blog_rss_feed) %> |
<%= link_to 'Back', admin_blog_rss_feeds_path %>