config/routes.rb
  post "/hdfc_secret" => "shopping_carts#hdfc_secret"
  post "/user_detail" => "shopping_carts#user_detail"

  get "/reset_countries" => "report_filters#reset_countries"
  post "/advance_search_countries" => "report_filters#advance_search_countries"
  
  resources :blogs, only: [:show,:index] do
    get 'blog_comments'
    collection do
      match "/category/:slug", :to => "blogs#blog_category",  :via => [:get, :post], :as => :blog_category
      match 'search' => 'blogs#search', :via => [:get, :post], :as => :blog_search
    end
  end
  get 'tags/:tag', to: 'blogs#index', as: :tag

  
  match 'blogs/by_year_and_month/:year/:month' => 'blogs#by_year_and_month', :via => [:get, :post], :as=> :blogs_by_year_and_month

  
  resources :user_sessions, only: [:new,:create,:destroy]
  
  post "/transaction/buynowccavRequestHandler" => "shopping_carts#buynowccavRequestHandler"
  match "/transaction/ccavRequestHandler" =>'shopping_carts#ccavRequestHandler', :via => [:get, :post]

  match "/transaction/ccavResponseHandler" =>'shopping_carts#ccavResponseHandler', :via => [:get, :post]
  match "/transaction/buynowCcavenueResponse" =>'shopping_carts#buynowCcavenueResponse', :via => [:get, :post]

  match "/transaction/cancel" =>'shopping_carts#cancel_transaction', :via => [:get, :post]
  resources :users, only: [:show,:new,:create]
  get 'signup' => 'users#new', :as => :signup

  root :to => 'home#index'

  get 'login'   => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout
  get 'signout' => 'user_sessions#destroy', as: :signout
  resources :password_resets, :only => [:new, :edit, :update]
  resources :news_updates, :only => [:show,:index], :path => '/press-release'
  namespace :admin do 
    resources :blogs do
      collection do
        get "blog_logs"
        get "blog_log_detail"
      end
    end
    match '/dashboard' => "dashboard#index", :via => ["get"], :as => :root
    match "/blogs/:id/delete", :to => "blogs#destroy", :via => ["delete"]
    match "/blog_rss_feeds/:id/delete", :to => "blog_rss_feeds#destroy", :via => ["delete"]
    resources :categories
    match "/categories/:id/delete", :to => "categories#destroy", :via => ["delete"]
    resources :publishers
    match "/publishers/:id/delete", :to => "publishers#destroy", :via => ["delete"]
    resources :pages
    resources :news_updates
    match "/news_updates/:id/delete", :to => "news_updates#destroy", :via => ["delete"]
    resources :reports do
      collection do
        match 'search' => 'reports#search', :via => [:get], :as => :search
        match 'search_reports' => 'reports#search_reports', :via => [:post]
        post :edit_multiple
        put :update_multiple
        post :upload_multiple
        post :save_position
        post :update_sheet
      end 

    end

    match "report_labels" =>'reports#report_labels', :via => [:get, :post]
    match "deactive_reports" =>'reports#deactive_reports', :via => [:get, :post]
    match "upload_files" => 'reports#upload_files', :via => [:get, :post]
    match "sort_reports" =>'reports#sort_reports', :via => [:get, :post]
   

    match "/reports/:id/delete", :to => "reports#destroy", :via => ["delete"]
    resources :messengers
    resources :conversations, only: [:show,:create] do
       resources :messengers
    end
    resources :orders
    resources :subscribers, :only => [:index, :show]  do 
      collection do
        post :toggle_active
      end
    end
    resources :testimonials
    match "/testimonials/:id/delete", :to => "testimonials#destroy", :via => ["delete"]
    match "/newsletter_templates/:id/delete", :to => "newsletter_templates#destroy", :via => ["delete"]
    match "/subscribers/:id/delete", :to => "subscribers#destroy", :via => ["delete"]
    match "order_details" =>'orders#order_details', :via => [:get, :post]
    resources :enquiries do
      collection do
        match 'list'=>"enquiries#list" ,:via=>[:get,:post]
        match 'list/:date'=>"enquiries#list_by_date" ,:via=>[:get,:post]
        match 'list/:date'=>"enquiries#delete_list" ,:via=>[:get,:delete]
        post :edit_multiple
      end
    end
   
    match "/pages/:id/delete", :to => "pages#destroy", :via => ["delete"]
    match "/enquiries/:id/delete_contact_us", :to => "enquiries#delete_contact_us", :via => ["delete"]
    
    match "/enquiries/:id/delete", :to => "enquiries#destroy", :via => ["delete"]
    match "contact_us" =>'enquiries#contact_us', :via => [:get, :post]
    match "/admin_change_password" => "dashboard#change_password", :via => [:get, :post]

    resources :newsletter_templates do 
      collection do
        post :send_multiple
        post :delete_multiple
      end
    end

    resources :clients
    match "/clients/:id/delete", :to => "clients#destroy", :via => ["delete"]
  end

  match "/send_password" => "password_resets#send_password" , :via=>[:post]
  match "/update_password" => "password_resets#update" , via: [:patch]
  match "/upload_excelsheet" => "admin/reports#upload_multiple" , via: [:post]
  match "/upload_reports" => "admin/reports#upload_reports" , via: [:post,:get]

  match "/upload_update_reports" => "admin/reports#upload_update_reports" , via: [:post,:get]

  resources :reports, only: [:show,:index]  do
    collection do
       match 'search' => 'reports#search', :via => [:get, :post], :as => :search
       get :get_all_reports
       get 'currency_section'
       post :show_advanced_search
    end 
    get :reset_filterrific, on: :collection    
  end 
  match "/reports/:id/:slug", :to => "reports#show", :via => ["get"]

  resources :categories, only: [:show,:index]

  resources :regions, only: [:show,:index] do
    member do
      match "/country_wise/:country_id", :to => "regions#country_wise", :via => ["get"]
    end
    collection do
      get 'reset_filter'
    end
  end
  resources :publishers, only: [:show,:index] do 
    collection do
      get 'load_more_publisher'
    end
  end
  resources :messages, only: [:create]
  resource :shopping_cart, only: [:show,:create]
  resources :pages, :only => [:show]
  match "/remove_item" => 'shopping_carts#remove_item', :via => [:get, :post]
  post "reports/enquiry" => "reports#enquiry"
  post "reports/enquiry_link" => "reports#enquiry_link"

  get "/clear_cart" => 'shopping_carts#clear_cart'
  get "/load_add_to_cart" => "shopping_carts#load_add_to_cart"
  get "/load_place_order_items" => "shopping_carts#load_place_order_items"

  post "/add_to_cart" => "shopping_carts#add_to_cart"
  

  post "blogs/post_comment" => "blogs#post_comment"

  get "/manage_address"  => 'shopping_carts#manage_address'
  get "/checkout"  => 'shopping_carts#checkout'
  get "/place_order"=> 'shopping_carts#place_order'
  get "/paypal_order_cancel"=> 'shopping_carts#paypal_order_cancel'
  get "/buynow_paypal_cancel"=> 'shopping_carts#buynow_paypal_cancel'
  resources :customers
  match "/update_quantity" => "shopping_carts#update_quantity", via: "post"
  match "/update_user" => "users#update_user", via: "post"
  match "/change_password" => "users#change_password", :via => [:get, :post]
  match "/update_password" => "users#update_password", :via => [:get, :post]
  match "/create_user" => "shopping_carts#create_user", via: "post"
  match "/signin_user" => "shopping_carts#signin_user", via: "post"
  match "/create_customer" => "shopping_carts#create_customer", via: "post"
  match "/complete_order" => "orders#complete_order", via: "post"
  match "/complete_ccavenue_order" => "orders#complete_ccavenue_order", :via => [:get, :post]

  match "/ccavenue_transfer" => "orders#ccavenue_transfer" , via: "post"
  match "/new_user_ccavenue_transfer" => "orders#new_user_ccavenue_transfer" , via: "post"
  
  match "/buynow_ccavenue_transfer" => "orders#buynow_ccavenue_transfer" , via: "post"

  get "purchase_complete" => "orders#purchase_complete"
  get "purchase_cancel" => "orders#purchase_cancel"
  
  get "checkout_complete" => "orders#checkout_complete"
  
  match "/express_checkout" => "orders#express_checkout", via: "post"
  match "/pay_checkout" => "orders#pay_checkout", via: "post"

  match "/wire_transfer" => "orders#wire_transfer", via: "post"
  get "/charges" , :controller=>"charges", :action=>"create"
  match "/save_chat_user" => "messages#save_chat_user", via: "post"
  resources :orders do
    collection do
      post 'send_to_ccavenue'
    end
  end
  resources :charges, only: [:new,:create]
  resources :continents, :only => [:index, :show] do
    collection do
      get 'global'
      get 'reset_filter_global'
      get 'reset_filter_continent'
    end
  end
  resources :countries, :only => [:index, :show] do
    collection do
      get 'reset_filter_country'
    end
  end
  match "/contact_us"=> "pages#contact_us", :via => [:get, :post], :path => '/contact-us'
  match "/save_contact_us" => "pages#save_contact_us", via: "post"
  match "/order_details" => "orders#order_details", :via => [:get, :post]
  match "/report_list" => "reports#continent_wise_reports", :via => [:get, :post]
  post "/email_report" => "reports#email_report"
  post "reports/subscriber" => "reports#subscriber"

  get "/allow" => "blogs#allow"
  get "/disallow" => "blogs#disallow"
  

  resources :conversations, only: [:show,:create] do
    resources :messages, only: [:create]
  end

  match "/wiretransfer_response" => "shopping_carts#wiretransfer", :via => [:get, :post]
  match "/paypal_purchase_complete" => "orders#paypal_purchase_complete", :via => [:get, :post]

  match "/hdfc/response" => "orders#hdfc_buynow_complete", :via => [:get, :post]
  
  match "/hdfc_complete" => "orders#hdfc_complete", :via => [:get, :post]

  match "/hdfc/cart_response" => "orders#hdfc_cart_complete", :via => [:get, :post]
  

  get "zohoverify/verifyforzoho.html" => "home#verifyforzoho" 
  get "order_page" => "pages#order_page" 
  get "load_tweets" => "home#load_tweets" 

  resources :authorizations, only: [:destroy,:create]

app/models/order.rb
class Order < ActiveRecord::Base

belongs_to  :user
belongs_to  :shopping_cart ,   :foreign_key => :cart_id
has_many    :order_details, dependent: :destroy


def purchase
  response = process_purchase
  transactions.create!(:action => "purchase", :amount => price_in_dollars, :response => response)
  cart.update_attribute(:purchased_at, Time.now) if response.success?
  response.success?
end

def express_token=(token)
  write_attribute(:express_token, token)
  if new_record? && !token.blank?
    details = EXPRESS_GATEWAY.details_for(token)
    self.express_payer_id = details.payer_id

    self.first_name = details.params["first_name"]
    self.last_name = details.params["last_name"]
  end
end


def self.create_order(ip_address,user,payment_method_type,order_id,report_id,price,edition)
  report = Report.search("@(id) '#{report_id}'").first
  json_data = JSON::parse(user.to_json(:include =>
     [:customer => {:include => [:country]
      }])).merge("payment_method_type" => payment_method_type,
                 "report_title"=> report.title,
                 "price"=> price,
                 "edition"=>edition).to_json 
  begin
    uri = URI.parse("http://crm.wiseguyreports.com/")
    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Post.new("/CRM/v1/CreateContact")
    request.add_field('Content-Type', 'application/json')
    request.body = json_data
    response = http.request(request)
  rescue
    puts "Error communicating with crm..."
  end 
end

private

def process_purchase
  if express_token.blank?
    STANDARD_GATEWAY.purchase(price_in_dollars, credit_card, standard_purchase_options)
  else
    EXPRESS_GATEWAY.purchase(price_in_dollars, express_purchase_options)
  end
end

def standard_purchase_options
  {
    :ip => ip_address,
    :billing_address => {
      :name     => "Ryan Bates",
      :address1 => "123 Main St.",
      :city     => "New York",
      :state    => "NY",
      :country  => "US",
      :zip      => "10001"
    }
  }
end

def express_purchase_options
  {
    :ip => ip_address,
    :token => express_token,
    :payer_id => express_payer_id
  }
end


def validate_card
  if express_token.blank? && !credit_card.valid?
    credit_card.errors.full_messages.each do |message|
      errors.add_to_base message
    end
  end
end	
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

	
  def index	
  	@orders = Order.paginate(:page => params[:page], :per_page => 10)
  end

  def order_details
  	@order_details = OrderDetail.where(order_id: params[:order_id])
  end
end

app/views/admin/orders/index.html.erb
<%= render "admin/shared/left_menu"%>
<div class="mainbar">

	<!-- Page heading -->
	<div class="page-head">
		<h2 class="pull-left"><i class="fa fa-file-o"></i> Orders</h2>

		<!-- Breadcrumb -->
		<div class="bread-crumb pull-right">
			<a href="/admin/dashboard"><i class="fa fa-home"></i> Home</a>
			<!-- Divider -->
			<span class="divider">/</span>
			<a href="#" class="bread-current">Orders</a>
		</div>

		<div class="clearfix"></div>

	</div>
	<!-- Page heading ends -->

	<!-- Matter -->

	<div class="matter">
		<div class="container">
			<div class="row">
				<div class="col-md-12">

					<div class="widget">
						<div class="widget-head">
							<div class="pull-left">
								Orders
							</div>
							
							<div class="clearfix"></div>
						</div>

						<%#= @category.nil? ? 'Main categories' : @category.name %>
						<table class="table table-striped table-bordered table-hover">
							<thead>
								<tr>
								
									<th>User Name</th>
									<th>Email</th>
									<th>Payment Type</th>
									<th>Order Total</th>
									<th>Order Status</th>
									
								</tr>
							</thead>
							<tbody>
							    <% @orders.each do |order| %>
								<tr>
								    <td><%= link_to order.user.first_name, admin_order_details_path(:order_id => order.id) %></td>
								     <td><%= order.user.email %></td>
								    <td> <%=order.payment_method_type %></td>
								    <td> <%=order.order_total %></td>
								    <td> <%=order.order_status %></td>
									<!--<td>
										<%#if current_user.is_superadmin%> 
										<%#= link_to 'Show'.html_safe, admin_order_path(order) %>
										<%#end%>
									</td>-->
								</tr>
								<% end %>

							</tbody>
						</table>

						<div class="widget-foot">
					
							<div class="pull-left">
								<%#= link_to  "Add News", new_admin_order_path, :class => 'btn btn-sm btn-primary' %>
							</div>

							<div class="pull-right">
								<%= will_paginate @orders, renderer: BootstrapPagination::Rails %>

							</div>

							<div class="clearfix"></div>

						</div>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/admin/orders/order_details.html.erb
<%= render "admin/shared/left_menu"%>
<div class="mainbar">

	<!-- Page heading -->
	<div class="page-head">
		<h2 class="pull-left"><i class="fa fa-file-o"></i> Orders</h2>

		<!-- Breadcrumb -->
		<div class="bread-crumb pull-right">
			<a href="/admin/dashboard"><i class="fa fa-home"></i> Home</a>
			<!-- Divider -->
			<span class="divider">/</span>
			<a href="#" class="bread-current">Orders</a>
		</div>

		<div class="clearfix"></div>

	</div>
	<!-- Page heading ends -->

	<!-- Matter -->

	<div class="matter">
		<div class="container">
			<div class="row">
				<div class="col-md-12">

					<div class="widget">
						<div class="widget-head">
							<div class="pull-left">
								Orders
							</div>
							
							<div class="clearfix"></div>
						</div>

						<%#= @category.nil? ? 'Main categories' : @category.name %>
						<table class="table table-striped table-bordered table-hover">
							<thead>
								<tr>
								
									<th>Report Title</th>
									<th>Price</th>
									<th>Quantity</th>
									<th>Status</th>
								
								
								</tr>
							</thead>
							<tbody>
							    <% @order_details.each do |order_detail| %>
								<tr>
								   
								     <td><%= Report.find(order_detail.report_id).title %></td>
								    <td> <%=order_detail.report_value %></td>
								    <td> <%=order_detail.quantity%></td>
								    <td> <%=order_detail.order_details_status %></td>
							
								</tr>
								<% end %>

							</tbody>
						</table>

						<div class="widget-foot">
					
							<div class="pull-left">
									<button type="button" onclick="javascript:history.back()", class="btn btn-sm btn-default">
											Back
										</button>
							</div>

							<div class="pull-right">
								<%#= will_paginate @orders, renderer: BootstrapPagination::Rails %>

							</div>

							<div class="clearfix"></div>

						</div>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/admin/orders/show.html.erb
<%= render "admin/shared/left_menu"%>
<div class="mainbar">

	<!-- Page heading -->
<div class="page-head">
		<h2 class="pull-left"><i class="fa fa-file-o"></i> Orders</h2>

		<!-- Breadcrumb -->
		<div class="bread-crumb pull-right">
			<a href="/admin/dashboard"><i class="fa fa-home"></i> Home</a>
			<!-- Divider -->
			<span class="divider">/</span>
			<a href="#" class="bread-current">Orders</a>
		</div>

		<div class="clearfix"></div>

	</div>
	<!-- Page heading ends -->

	<!-- Matter -->
	<div class="matter">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="widget">
						<div class="widget-head">
							<div class="pull-left">
								Blog log Detail
							</div>
						
							<div class="clearfix"></div>
						</div>
						<div class="widget-content">
							<div class="padd">
								<br/>
						
								

<p>
    <strong>Title:</strong>&nbsp;&nbsp;&nbsp;
	<%if @blog_log.action == "destroy"%>
	  <td><%=  @blog_log.audited_changes.split(":")[1].split("\n")[0]%></td>
	<%else%>
	 <%if  @blog_log.auditable_type == "NewsUpdate" %>
                      <td><a href="/admin/blogs/blog_log_detail?id=<%= @blog_log.id%>"><%=NewsUpdate.find( @blog_log.auditable_id).title %></a></td>
                     <%else%>
                      <td><a href="/admin/blogs/blog_log_detail?id=<%= @blog_log.id%>"><%=Admin::Blog.find( @blog_log.auditable_id).title %></a></td>
                    <%end%>
	<%end%>
</p>


<p>
  <strong>Type:</strong>&nbsp;&nbsp;&nbsp;
  <%=  @blog_log.auditable_type%>
</p>


<p>
  <strong>By:</strong>&nbsp;&nbsp;&nbsp;
  <%=  User.find(@blog_log.user_id).email%>
</p>

<p>
  <strong>Action:</strong>&nbsp;&nbsp;&nbsp;
  <span class="label label-<%= get_action_color(@blog_log.action)%>"><%=  @blog_log.action%></span>
</p>
<!--<p>
  <strong>Changes:</strong>&nbsp;&nbsp;&nbsp;
  <%#=  @blog_log.audited_changes.html_safe %>
</p> -->
<p>
  <strong>Ip Address:</strong>&nbsp;&nbsp;&nbsp;
  <%=  @blog_log.remote_address%>
</p>

<p>
  <strong>Created On:</strong>&nbsp;&nbsp;&nbsp;
 <%=  @blog_log.created_at.strftime("%A, " "%d " "%B, %Y")%>
</p>							</div>



    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-6">

        <button type="button" onclick="javascript:history.back()", class="btn btn-sm btn-default">
          Back
        </button>
      </div>
    </div>
<br/><br/>
						</div>
						<div class="widget-foot">

							<div class="clearfix"></div>

						</div>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>