config/routes.rb
Rails.application.routes.draw do

  match "/report_back", :to => "reports#lolcat", :via => [:get]
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  namespace :admin do
    resources :blog_rss_feeds
  end

  get "/rss-feeds" =>"home#rss_feeds"
  get "/rss/category/:id" => "home#get_rss_feed_of_category"
  get "/rss/publisher/:id" => "home#get_rss_feed_of_publisher"
  get "/rss/countries/:id" => "home#get_rss_feed_of_country"
  get "/rss/continents/:id" => "home#get_rss_feed_of_continents"
  get "/rss/regions/:id" => "home#get_rss_feed_of_regions"
  get "/rss/news-and-update" => "home#get_rss_feed_of_news_and_update"
  get "/rss/latest-reports" => "home#get_latest_reports"
  get "/rss/top-selling-reports" => "home#get_top_selling_reports"
  get "/rss/upcoming-reports" => "home#get_rss_feed_of_upcoming_reports"
  get "/rss/popular-categories" => "home#get_rss_feed_of_popular_categories"
  post "/show_side_panel_of_category" => "home#show_side_panel_of_category"

  post "/show_all_publishers" => "report_filters#show_all_publishers"
  post "/show_default_publishers" => "report_filters#show_default_publishers"
  post "/show_filter_reports" => "report_filters#show_filter_reports"
  get "/get_all_publishers" => "report_filters#get_all_publishers"
  get "/sort_publishers/:name" =>"report_filters#sort_publishers"
  post "/show_all_countries" => "report_filters#show_all_countries"
  post "/show_all_categories" => "report_filters#show_all_categories" 
  post "/show_all_continents" => "report_filters#show_all_continents"
  post "/show_all_regions" => "report_filters#show_all_regions"
  post "/show_selected_regions" => "report_filters#show_selected_regions"
  post "/show_selected_continents" => "report_filters#show_selected_continents"
  post "/reset_to_default_by_category" => "categories#reset_to_default_by_category"
  post "/new_report_enquiry" => "home#new_report_enquiry"
  post "/hdfc_secret" => "shopping_carts#hdfc_secret"
  post "/user_detail" => "shopping_carts#user_detail"

  get "/reset_countries" => "report_filters#reset_countries"
  post "/advance_search_countries" => "report_filters#advance_search_countries"
  
  resources :blogs, only: [:show,:index] do
    get 'blog_comments'
    collection do
      match "/category/:slug", :to => "blogs#blog_category",  :via => [:get, :post], :as => :blog_category
      match 'search' => 'blogs#search', :via => [:get, :post], :as => :blog_search
    end
  end
  get 'tags/:tag', to: 'blogs#index', as: :tag

  
  match 'blogs/by_year_and_month/:year/:month' => 'blogs#by_year_and_month', :via => [:get, :post], :as=> :blogs_by_year_and_month

  
  resources :user_sessions, only: [:new,:create,:destroy]
  
  post "/transaction/buynowccavRequestHandler" => "shopping_carts#buynowccavRequestHandler"
  match "/transaction/ccavRequestHandler" =>'shopping_carts#ccavRequestHandler', :via => [:get, :post]

  match "/transaction/ccavResponseHandler" =>'shopping_carts#ccavResponseHandler', :via => [:get, :post]
  match "/transaction/buynowCcavenueResponse" =>'shopping_carts#buynowCcavenueResponse', :via => [:get, :post]

  match "/transaction/cancel" =>'shopping_carts#cancel_transaction', :via => [:get, :post]
  resources :users, only: [:show,:new,:create]
  get 'signup' => 'users#new', :as => :signup

  root :to => 'home#index'

  get 'login'   => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout
  get 'signout' => 'user_sessions#destroy', as: :signout
  resources :password_resets, :only => [:new, :edit, :update]
  resources :news_updates, :only => [:show,:index], :path => '/press-release'
  namespace :admin do 
    resources :blogs do
      collection do
        get "blog_logs"
        get "blog_log_detail"
      end
    end
    match '/dashboard' => "dashboard#index", :via => ["get"], :as => :root
    match "/blogs/:id/delete", :to => "blogs#destroy", :via => ["delete"]
    match "/blog_rss_feeds/:id/delete", :to => "blog_rss_feeds#destroy", :via => ["delete"]
    resources :categories
    match "/categories/:id/delete", :to => "categories#destroy", :via => ["delete"]
    resources :publishers
    match "/publishers/:id/delete", :to => "publishers#destroy", :via => ["delete"]
    resources :pages
    resources :news_updates
    match "/news_updates/:id/delete", :to => "news_updates#destroy", :via => ["delete"]
    resources :reports do
      collection do
        match 'search' => 'reports#search', :via => [:get], :as => :search
        match 'search_reports' => 'reports#search_reports', :via => [:post]
        post :edit_multiple
        put :update_multiple
        post :upload_multiple
        post :save_position
        post :update_sheet
      end 

    end

    match "report_labels" =>'reports#report_labels', :via => [:get, :post]
    match "deactive_reports" =>'reports#deactive_reports', :via => [:get, :post]
    match "upload_files" => 'reports#upload_files', :via => [:get, :post]
    match "sort_reports" =>'reports#sort_reports', :via => [:get, :post]
   

    match "/reports/:id/delete", :to => "reports#destroy", :via => ["delete"]
    resources :messengers
    resources :conversations, only: [:show,:create] do
       resources :messengers
    end
    resources :orders
    resources :subscribers, :only => [:index, :show]  do 
      collection do
        post :toggle_active
      end
    end
    resources :testimonials
    match "/testimonials/:id/delete", :to => "testimonials#destroy", :via => ["delete"]
    match "/newsletter_templates/:id/delete", :to => "newsletter_templates#destroy", :via => ["delete"]
    match "/subscribers/:id/delete", :to => "subscribers#destroy", :via => ["delete"]
    match "order_details" =>'orders#order_details', :via => [:get, :post]
    resources :enquiries do
      collection do
        match 'list'=>"enquiries#list" ,:via=>[:get,:post]
        match 'list/:date'=>"enquiries#list_by_date" ,:via=>[:get,:post]
        match 'list/:date'=>"enquiries#delete_list" ,:via=>[:get,:delete]
        post :edit_multiple
      end
    end
   
    match "/pages/:id/delete", :to => "pages#destroy", :via => ["delete"]
    match "/enquiries/:id/delete_contact_us", :to => "enquiries#delete_contact_us", :via => ["delete"]
    
    match "/enquiries/:id/delete", :to => "enquiries#destroy", :via => ["delete"]
    match "contact_us" =>'enquiries#contact_us', :via => [:get, :post]
    match "/admin_change_password" => "dashboard#change_password", :via => [:get, :post]

    resources :newsletter_templates do 
      collection do
        post :send_multiple
        post :delete_multiple
      end
    end

    resources :clients
    match "/clients/:id/delete", :to => "clients#destroy", :via => ["delete"]
  end

  match "/send_password" => "password_resets#send_password" , :via=>[:post]
  match "/update_password" => "password_resets#update" , via: [:patch]
  match "/upload_excelsheet" => "admin/reports#upload_multiple" , via: [:post]
  match "/upload_reports" => "admin/reports#upload_reports" , via: [:post,:get]

  match "/upload_update_reports" => "admin/reports#upload_update_reports" , via: [:post,:get]

  resources :reports, only: [:show,:index]  do
    collection do
       match 'search' => 'reports#search', :via => [:get, :post], :as => :search
       get :get_all_reports
       get 'currency_section'
       post :show_advanced_search
    end 
    get :reset_filterrific, on: :collection    
  end 
  match "/reports/:id/:slug", :to => "reports#show", :via => ["get"]

  resources :categories, only: [:show,:index]

  resources :regions, only: [:show,:index] do
    member do
      match "/country_wise/:country_id", :to => "regions#country_wise", :via => ["get"]
    end
    collection do
      get 'reset_filter'
    end
  end
  resources :publishers, only: [:show,:index] do 
    collection do
      get 'load_more_publisher'
    end
  end
  resources :messages, only: [:create]
  resource :shopping_cart, only: [:show,:create]
  resources :pages, :only => [:show]
  match "/remove_item" => 'shopping_carts#remove_item', :via => [:get, :post]
  post "reports/enquiry" => "reports#enquiry"
  post "reports/enquiry_link" => "reports#enquiry_link"

  get "/clear_cart" => 'shopping_carts#clear_cart'
  get "/load_add_to_cart" => "shopping_carts#load_add_to_cart"
  get "/load_place_order_items" => "shopping_carts#load_place_order_items"

  post "/add_to_cart" => "shopping_carts#add_to_cart"
  

  post "blogs/post_comment" => "blogs#post_comment"

  get "/manage_address"  => 'shopping_carts#manage_address'
  get "/checkout"  => 'shopping_carts#checkout'
  get "/place_order"=> 'shopping_carts#place_order'
  get "/paypal_order_cancel"=> 'shopping_carts#paypal_order_cancel'
  get "/buynow_paypal_cancel"=> 'shopping_carts#buynow_paypal_cancel'
  resources :customers
  match "/update_quantity" => "shopping_carts#update_quantity", via: "post"
  match "/update_user" => "users#update_user", via: "post"
  match "/change_password" => "users#change_password", :via => [:get, :post]
  match "/update_password" => "users#update_password", :via => [:get, :post]
  match "/create_user" => "shopping_carts#create_user", via: "post"
  match "/signin_user" => "shopping_carts#signin_user", via: "post"
  match "/create_customer" => "shopping_carts#create_customer", via: "post"
  match "/complete_order" => "orders#complete_order", via: "post"
  match "/complete_ccavenue_order" => "orders#complete_ccavenue_order", :via => [:get, :post]

  match "/ccavenue_transfer" => "orders#ccavenue_transfer" , via: "post"
  match "/new_user_ccavenue_transfer" => "orders#new_user_ccavenue_transfer" , via: "post"
  
  match "/buynow_ccavenue_transfer" => "orders#buynow_ccavenue_transfer" , via: "post"

  get "purchase_complete" => "orders#purchase_complete"
  get "purchase_cancel" => "orders#purchase_cancel"
  
  get "checkout_complete" => "orders#checkout_complete"
  
  match "/express_checkout" => "orders#express_checkout", via: "post"

app/models/category.rb
class Category < ActiveRecord::Base
  include Tree
  mount_uploader :category_report_image, CategoryReportImageUploader
  has_many :reports, :dependent => :destroy
  has_many :news_updates, :dependent => :destroy
  has_many :blogs, :dependent => :destroy, :class_name => "Admin::Blog"
  has_many :publishers, through: :reports
  has_many :country_reports, through: :reports
  has_many :countries, {:through=>:reports, :source=>:country}
  has_many :regions, through: :country_reports
  has_many :continents, through: :countries
  extend FriendlyId
  friendly_id :name, use: :slugged
  before_save   :cache_ancestry
  before_update :cache_ancestry
  before_create :cache_ancestry 
  after_save :expire_cache

  def cache_ancestry
    self.name = self.name.strip     
  end

  def reports
    Report.where("category_id in (?)", self.subtree.pluck("id")) 
  end

  def publishers
    publisher_count = Publisher.search(:sql=>{:select=>"publishers.id"}).total_entries
    Publisher.search(:max_matches => publisher_count,:with=>{:category_ids=>self.subtree.pluck("id")})
  end

  def self.get_all_categories
    Rails.cache.fetch("all-categories") do
      Category.search(:sql => {:select => "id,slug,name,reports_count" }, :with => {:root_ancestry => 0},:order=>"category_name asc").to_a
    end
  end

  def self.options_for_select
    Category.roots.all.map { |e| [e.name, e.id] }
  end

  def expire_cache
    Rails.cache.delete("report_category_count")
  end

  def self.category_hash
    Rails.cache.fetch("category-hash") do
      category_count = Category.search(:sql=>{:select=>"categories.id"}).total_entries
      Category.search(:sql => {:select => "id,slug,name" }, :with => {:root_ancestry => 0},:per_page=>category_count).to_a.inject({}) {|i,n| i.merge({n.id => {:name => n.name, :slug => n.slug}})}
    end
  end

  def self.sphinx_get_child_ids(categories_ids)
    category_count = Category.search(:sql=>{:select=>"categories.id"}).total_entries
    Category.search(:with => {:root_ancestry => categories_ids},:sql=>{:select=>"id"},:per_page=>category_count).map(&:id)
  end

  def self.get_category_and_subcategory(categories_ids)
    category_ids = categories_ids
    category_ids.push(Category.sphinx_get_child_ids(categories_ids))
    category_ids.flatten
  end

  def self.recount_report_count
    all.each do |category|
      category_count = Category.search(:sql=>{:select=>"categories.id"}).total_entries
      category_ids = [category.id,Category.search(:with => {:root_ancestry => category.id},:sql => { :select => "id" },:per_page=>category_count).map(&:id)].flatten
      new_reports_count = Report.search(:with => {:upcoming => 0, :category_id => category_ids}, :sql => {:select => 'reports.id'}).total_entries
      category.update_attribute('reports_count',new_reports_count)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
  acts_as_authentic do |c|
    c.login_field = 'email'
    c.validate_login_field = false;
    c.validates_length_of_password_field_options( :minimum => 6, :on => :update, :if => :password_changed? )
  end 
  has_one     :customer , dependent: :destroy
  has_one     :shopping_cart
  has_many    :orders , dependent: :destroy
  has_many    :order_details, through: :orders
  has_many    :reports,  through: :order_details
  has_many    :categories, through: :reports
  has_many    :authorizations, :dependent => :destroy
  extend FriendlyId
  friendly_id :full_name, use: :slugged
  serialize :omniauth_data, JSON

  accepts_nested_attributes_for :customer

  
  def full_name
    first_name.to_s.capitalize + " " + last_name.to_s.capitalize
  end
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    #UserMailer.delay(run_at: Time.now).password_reset(self)
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def self.create_from_omniauth_data(omniauth_data)
    user = User.new(
      :first_name => omniauth_data['info']['first_name'].to_s.downcase,
      :last_name => omniauth_data['info']['last_name'].to_s.downcase,
      :email => omniauth_data['info']['email'].to_s.downcase,
      :password => (0...50).map { ('a'..'z').to_a[rand(26)] }.join,
      :single_access_token => omniauth_data.extra.access_token.token
      )
    user.omniauth_data = omniauth_data.to_json #shove OmniAuth::AuthHash as json data to be parsed later!

    user.save(:validate => false) #create without validations because most of the fields are not set.
    user.reset_persistence_token! #set persistence_token else sessions will not be created
    user
  end

  def self.build_cache
    puts "caching categories..."
    Category.all.each do |category|
      Rails.cache.delete("related-reports-#{category.id}")
      Report.related_report(category.id)
    end

    Rails.cache.delete("all-categories")
    Category.get_all_categories
    Rails.cache.delete("category-hash")
    Category.category_hash

    puts "caching continents..."
    Continent.list
    Rails.cache.delete("continent-list")
    Continent.all.each do |continent|
      Rails.cache.delete("get-continent-reports-#{continent.id}")
      Report.get_continent_reports(continent.id)
    end
    
    puts "caching countries...."
    Rails.cache.delete("all-countries")
    Country.get_all_countries
    Rails.cache.delete("country-list")
    Country.list
    Country.select("id,abbreviation").each do |country|
      Rails.cache.delete("get-country-reports-#{country.id}")
      Report.get_country_reports(country.abbreviation)
    end

    puts "caching regions..."
    Rails.cache.delete("all_regions")
    Region.all_regions
    Region.select("id").each do |region|
      Rails.cache.delete("region-#{region.id}-report-count")
      region.report_count
      Rails.cache.delete("get-region-reports-#{region.id}")
      Report.get_region_reports(region.id)
    end
    puts "caching reports...."
    Rails.cache.delete("upcoming-reports")
    Report.upcoming_reports
    Rails.cache.delete("latest-reports")
    Report.latest_reports
    Rails.cache.delete("topselling-reports")
    Report.topselling
    Rails.cache.delete("get-global-reports")
    Report.cached_global
    puts "caching publishers......"
    Publisher.select("id").each do |publisher|
      (1..10).to_a.each {|page_index| 
        Rails.cache.delete("get-publisher-reports-#{publisher.id}-#{page_index}")
        Report.get_publisher_reports(publisher.id,page_index)
      }
      Rails.cache.delete("get-topselling-publisher-reports-#{publisher.id}")
      Report.get_topselling_publisher_reports(publisher.id)
    end

    puts "caching news updates..."
    Rails.cache.delete("news-update-list")
    NewsUpdate.list
    NewsUpdate.where("category_id != NULL").select("id").each do |news|
      Rails.cache.delete("get-newsrelated-reports-#{news.id}")
      Report.get_news_related_reports(news.id)
    end
    puts "caching testimonials...."
    Rails.cache.delete("testimonial-list")
    Testimonial.list

    puts "Delete global count cache"
    Rails.cache.delete('global-count')
    Report.global_count
    Rails.cache.delete("tweet-list")
  end
end

app/views/admin/reports/index.html.erb
<style type="text/css">
.pretty th .current {
  padding-right: 12px;
  background-repeat: no-repeat;
  background-position: right center;
}

.pretty th .asc {
  background-image: url(/assets/sort_asc.png);
}

.pretty th .desc {
  background-image: url(/assets/sort_desc.png);
}

</style>



<%= render "admin/shared/left_menu"%>
<div class="mainbar">

	<!-- Page heading -->
	<div class="page-head">
		<h2 class="pull-left"><i class="fa fa-file-o"></i> Reports</h2>

		<!-- Breadcrumb -->
		<div class="bread-crumb pull-right">
			<a href="/admin/dashboard"><i class="fa fa-home"></i> Home</a>
			<!-- Divider -->
			<span class="divider">/</span>
			<a href="#" class="bread-current">Reports</a>
		</div>

		<div class="clearfix"></div>

	</div>
	<!-- Page heading ends -->

	<!-- Matter -->

	<div class="matter">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
				<%if params[:action] == "search"%>
					<button type="button" onclick="javascript:history.back()", class="btn btn-sm btn-default">
						Back to Result
					</button>
				<%end%>
				<div class="widget">
					<div class="widget-head">
						<div class="pull-left">
							Reports
						</div>
					
						<div class="clearfix"></div>
					</div>
       <div id="reports">
		<%= hidden_field_tag :direction, params[:direction] %>
		<%= hidden_field_tag :sort, params[:sort] %>
	
		<table class="table table-striped table-bordered table-hover">
			<thead><%= form_tag admin_reports_path, :method => "GET" do |f| %>
			<thead>
				<tr>
				<td></td>
				<td>

				  <%= text_field_tag "report[title]",(params[:report][:title] rescue nil),:class=>"form-control", :placeholder=>"Report title" %>
				</td>
				<td>
		
				  <%= text_field_tag "report[publisher_name]" ,(params[:report][:publisher_name] rescue nil),:class=>"form-control", :placeholder=>"Publisher"%>
				</td>
		
				<td>
					<div class="col-md-5">
					  <%= text_field_tag "report[day]",(params[:report][:day] rescue nil),:class=>"form-control", :placeholder=>"Date"%>
					</div>
					<div class="col-sm-7">
				    <%= text_field_tag "report[publish_month]",(params[:report][:publish_month] rescue nil),:class=>"form-control", :placeholder=>"Month"%>
					</div>
				</td>
				<td>
			
				  <%= text_field_tag "report[one_user]",(params[:report][:one_user] rescue nil),:class=>"form-control", :placeholder=>"Price"%>
				</td>

				<td>
				  <%= submit_tag  "Search", :class=>"btn btn-sm btn-success",:onclick=> " return validateMonth();" %>
				   <a href="/admin/reports" class="btn btn-sm btn-default">Reset!</a>
				</td>




				</tr><% end %>
				<tr>
					<th><input type="checkbox" id="selectAll" value="selectAll">All</th>
				    <th style="width: 30%;" class="pretty">Report Name</th>
				    <th style="width: 20%;" class="pretty">Publisher Name</th>
				    <th style="width: 23%;" class="pretty">Publish Date</th>
				    <th style="width: 10%;" class="pretty">Price</th>
					<th style="width: 15%;" >Action</th>
				</tr>
			</thead>
			<tbody>
				<%= form_tag edit_multiple_admin_reports_path, method: :post do %>
			
				<tr>
				  <%if current_user.is_superadmin%>
				  <td><%= submit_tag "Edit Selected", :class => 'btn btn-sm btn-default'  %></td> <td><%= submit_tag 'Delete Selected', :class => 'btn btn-sm btn-danger' , :name => 'delete_button', :onclick=>"if(confirm('Are you sure you want to delete the selected reports?'))  return true;  else  return false;" %> </td>
				  <%end%>
				</tr>
				
				<% @reports.each do |report| %>
				<tr>
					<td><%= check_box_tag "report_ids[]", report.id %></td>
				    <td><%= report.title %></td>
				   
				    <td><%= report.publisher.name rescue nil %></td>
				     <td><%= report.day rescue nil%> <%= report.publish_month.to_date.strftime("%B, %Y") rescue nil%></td>
				    <td> <i class="fa fa-usd"></i><%= report.one_user %></td>
					<td>
						<%if current_user.is_superadmin%>
						<%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_report_path(report) , :class=>'btn btn-xs btn-warning'  %> <a href="/admin/reports/<%= report.id %>/delete" data-confirm="Are you sure?" data-method="delete" class="btn btn-xs btn-danger" ><i class="fa fa-times"></i> </a>
						<%end%>


					</td>
				</tr>

				<% end %>
				
				<tr>
					<%if current_user.is_superadmin%>
				    <td><%= submit_tag "Edit Selected", :class => 'btn btn-sm btn-default'  %></td> <td><%= submit_tag 'Delete Selected', :class => 'btn btn-sm btn-danger' , :name => 'delete_button', :onclick=>"if(confirm('Are you sure you want to delete the selected reports?'))  return true;  else  return false;" %> </td>
				    <% end %>
				</tr>
				
			<% end %>
			</tbody>
		</table>
  </div>

				
	<div class="widget-foot">

		<div class="pull-left">
			<%= link_to  "Add Report", new_admin_report_path, :class => 'btn btn-sm btn-primary' %>
			<%= link_to  "Import Report(.xlsx)", upload_reports_path, :class => 'btn btn-sm btn-primary' %>
			<%#= link_to  "Update Report(.xlsx)", upload_update_reports_path, :class => 'btn btn-sm btn-primary' %>
		</div>

	
		<div class="pull-right">

	    <%unless params[:q].present?%>
		<%= page_entries_info @reports %>	<br/><%= will_paginate @reports, renderer: BootstrapPagination::Rails %>
		<%end%>
		</div>

		<div class="clearfix"></div>

	</div>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>



<script language="Javascript" type="text/javascript" src="//code.jquery.com/jquery-1.9.1.js"></script>
<script language="Javascript" type="text/javascript" src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">

<script type="text/javascript">

jQuery(document).ready(function() {
	
jQuery('#report_publish_month').monthpicker({pattern: 'yyyy/mm'});
});
</script>


<script type="text/javascript">
var jq = jQuery.noConflict(); 

jq('#selectAll').click(function() {
   if(this.checked) {
       jq(':checkbox').each(function() {
           this.checked = true;                        
       });
   } else {
      jq(':checkbox').each(function() {
           this.checked = false;                        
       });
   } 
});

function validateMonth(){
	if(jq("#report_day").val().length > 0 && !jq("#report_publish_month").val().length > 0){
		alert("Please select Month and Year")
		return false;
	}else{
		return true;
	}
}
</script>

app/views/admin/reports/index.js.erb
$("#reports").html("<%= escape_javascript(render("reports")) %>");

app/views/admin/reports/report_labels.html.erb
<%= render "admin/shared/left_menu"%>
<div class="mainbar">

	<!-- Page heading -->
	<div class="page-head">
		<h2 class="pull-left"><i class="fa fa-file-o"></i> Reports</h2>

		<!-- Breadcrumb -->
		<div class="bread-crumb pull-right">
			<a href="/admin/dashboard"><i class="fa fa-home"></i> Home</a>
			<!-- Divider -->
			<span class="divider">/</span>
			<a href="#" class="bread-current">Reports</a>
		</div>

		<div class="clearfix"></div>

	</div>
	<!-- Page heading ends -->

	<!-- Matter -->

	<div class="matter">
		<div class="container">
			<div class="row">
				<div class="col-md-12">

					<div class="widget">
						<div class="widget-head">
							<div class="pull-left">
								Reports
							</div>
						
							<div class="clearfix"></div>
						</div>
			  <%= form_for(:report, :url => admin_sort_reports_path,  :class=>"form-horizontal", :html => { :id=>"report_label",:onsubmit=>"return jQuery('#report_label').validationEngine('validate',{scroll: false});" }) do |f| %>
					<div class="form-group">
					
						<div class="col-lg-3">
						


							 <%= f.select :report_type, options_for_select(Report::REPORT_TYPES) ,{:prompt => "--select category--"} ,:class=>"form-control validate[required]" %>
						</div>
					</div>




						<button type="submit" class="btn btn-sm btn-success">
																	Find
																</button>

						<%end%>


						<br>
						<br><br>
							<div id="loading" style="display:none">
						 		<img src="/assets/loader.gif"/>
						 	</div>
						 <div id ="reports">
						 
						  <%#= render "update_reports"%>

						 </div>


						
						<div class="widget-foot">
					
						

							<div class="clearfix"></div>

						</div>

					</div>
				</div>

			</div>
		</div>
	</div>
</div>




<script language="Javascript" type="text/javascript" src="//code.jquery.com/jquery-1.9.1.js"></script>
<script language="Javascript" type="text/javascript" src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
<script type="text/javascript">

jQuery(document).ready(function() {
	
jQuery('#q_publish_month_eq').monthpicker();




});

// jQuery( "#report_label" ).submit(function( event ) {
//  jQuery("#report_label").validationEngine('validate',{promptPosition : "centerRight", scroll: false})
//  return false;
// });

</script>


<script type="text/javascript">
var jq = jQuery.noConflict(); 

jq('#selectAll').click(function() {
   if(this.checked) {
       jq(':checkbox').each(function() {
           this.checked = true;                        
       });
   } else {
      jq(':checkbox').each(function() {
           this.checked = false;                        
       });
   } 
});
</script>