config/routes.rb
Rails.application.routes.draw do

  match "/report_back", :to => "reports#lolcat", :via => [:get]
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  namespace :admin do
    resources :blog_rss_feeds
  end

  get "/rss-feeds" =>"home#rss_feeds"
  get "/rss/category/:id" => "home#get_rss_feed_of_category"
  get "/rss/publisher/:id" => "home#get_rss_feed_of_publisher"
  get "/rss/countries/:id" => "home#get_rss_feed_of_country"
  get "/rss/continents/:id" => "home#get_rss_feed_of_continents"
  get "/rss/regions/:id" => "home#get_rss_feed_of_regions"
  get "/rss/news-and-update" => "home#get_rss_feed_of_news_and_update"
  get "/rss/latest-reports" => "home#get_latest_reports"
  get "/rss/top-selling-reports" => "home#get_top_selling_reports"
  get "/rss/upcoming-reports" => "home#get_rss_feed_of_upcoming_reports"
  get "/rss/popular-categories" => "home#get_rss_feed_of_popular_categories"
  post "/show_side_panel_of_category" => "home#show_side_panel_of_category"

  post "/show_all_publishers" => "report_filters#show_all_publishers"
  post "/show_default_publishers" => "report_filters#show_default_publishers"
  post "/show_filter_reports" => "report_filters#show_filter_reports"
  get "/get_all_publishers" => "report_filters#get_all_publishers"
  get "/sort_publishers/:name" =>"report_filters#sort_publishers"
  post "/show_all_countries" => "report_filters#show_all_countries"
  post "/show_all_categories" => "report_filters#show_all_categories" 
  post "/show_all_continents" => "report_filters#show_all_continents"
  post "/show_all_regions" => "report_filters#show_all_regions"
  post "/show_selected_regions" => "report_filters#show_selected_regions"
  post "/show_selected_continents" => "report_filters#show_selected_continents"
  post "/reset_to_default_by_category" => "categories#reset_to_default_by_category"
  post "/new_report_enquiry" => "home#new_report_enquiry"
  post "/hdfc_secret" => "shopping_carts#hdfc_secret"
  post "/user_detail" => "shopping_carts#user_detail"

  get "/reset_countries" => "report_filters#reset_countries"
  post "/advance_search_countries" => "report_filters#advance_search_countries"
  
  resources :blogs, only: [:show,:index] do
    get 'blog_comments'
    collection do
      match "/category/:slug", :to => "blogs#blog_category",  :via => [:get, :post], :as => :blog_category
      match 'search' => 'blogs#search', :via => [:get, :post], :as => :blog_search
    end
  end
  get 'tags/:tag', to: 'blogs#index', as: :tag

  
  match 'blogs/by_year_and_month/:year/:month' => 'blogs#by_year_and_month', :via => [:get, :post], :as=> :blogs_by_year_and_month

  
  resources :user_sessions, only: [:new,:create,:destroy]
  
  post "/transaction/buynowccavRequestHandler" => "shopping_carts#buynowccavRequestHandler"
  match "/transaction/ccavRequestHandler" =>'shopping_carts#ccavRequestHandler', :via => [:get, :post]

  match "/transaction/ccavResponseHandler" =>'shopping_carts#ccavResponseHandler', :via => [:get, :post]
  match "/transaction/buynowCcavenueResponse" =>'shopping_carts#buynowCcavenueResponse', :via => [:get, :post]

  match "/transaction/cancel" =>'shopping_carts#cancel_transaction', :via => [:get, :post]
  resources :users, only: [:show,:new,:create]
  get 'signup' => 'users#new', :as => :signup

  root :to => 'home#index'

  get 'login'   => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout
  get 'signout' => 'user_sessions#destroy', as: :signout
  resources :password_resets, :only => [:new, :edit, :update]
  resources :news_updates, :only => [:show,:index], :path => '/press-release'
  namespace :admin do 
    resources :blogs do
      collection do
        get "blog_logs"
        get "blog_log_detail"
      end
    end
    match '/dashboard' => "dashboard#index", :via => ["get"], :as => :root
    match "/blogs/:id/delete", :to => "blogs#destroy", :via => ["delete"]
    match "/blog_rss_feeds/:id/delete", :to => "blog_rss_feeds#destroy", :via => ["delete"]
    resources :categories
    match "/categories/:id/delete", :to => "categories#destroy", :via => ["delete"]
    resources :publishers
    match "/publishers/:id/delete", :to => "publishers#destroy", :via => ["delete"]
    resources :pages
    resources :news_updates
    match "/news_updates/:id/delete", :to => "news_updates#destroy", :via => ["delete"]
    resources :reports do
      collection do
        match 'search' => 'reports#search', :via => [:get], :as => :search
        match 'search_reports' => 'reports#search_reports', :via => [:post]
        post :edit_multiple
        put :update_multiple
        post :upload_multiple
        post :save_position
        post :update_sheet
      end 

    end

    match "report_labels" =>'reports#report_labels', :via => [:get, :post]
    match "deactive_reports" =>'reports#deactive_reports', :via => [:get, :post]
    match "upload_files" => 'reports#upload_files', :via => [:get, :post]
    match "sort_reports" =>'reports#sort_reports', :via => [:get, :post]
   

    match "/reports/:id/delete", :to => "reports#destroy", :via => ["delete"]
    resources :messengers
    resources :conversations, only: [:show,:create] do
       resources :messengers
    end
    resources :orders
    resources :subscribers, :only => [:index, :show]  do 
      collection do
        post :toggle_active
      end
    end
    resources :testimonials
    match "/testimonials/:id/delete", :to => "testimonials#destroy", :via => ["delete"]
    match "/newsletter_templates/:id/delete", :to => "newsletter_templates#destroy", :via => ["delete"]
    match "/subscribers/:id/delete", :to => "subscribers#destroy", :via => ["delete"]
    match "order_details" =>'orders#order_details', :via => [:get, :post]
    resources :enquiries do
      collection do
        match 'list'=>"enquiries#list" ,:via=>[:get,:post]
        match 'list/:date'=>"enquiries#list_by_date" ,:via=>[:get,:post]
        match 'list/:date'=>"enquiries#delete_list" ,:via=>[:get,:delete]
        post :edit_multiple
      end
    end
   
    match "/pages/:id/delete", :to => "pages#destroy", :via => ["delete"]
    match "/enquiries/:id/delete_contact_us", :to => "enquiries#delete_contact_us", :via => ["delete"]
    
    match "/enquiries/:id/delete", :to => "enquiries#destroy", :via => ["delete"]
    match "contact_us" =>'enquiries#contact_us', :via => [:get, :post]
    match "/admin_change_password" => "dashboard#change_password", :via => [:get, :post]

    resources :newsletter_templates do 
      collection do
        post :send_multiple
        post :delete_multiple
      end
    end

    resources :clients
    match "/clients/:id/delete", :to => "clients#destroy", :via => ["delete"]
  end

  match "/send_password" => "password_resets#send_password" , :via=>[:post]
  match "/update_password" => "password_resets#update" , via: [:patch]
  match "/upload_excelsheet" => "admin/reports#upload_multiple" , via: [:post]
  match "/upload_reports" => "admin/reports#upload_reports" , via: [:post,:get]

  match "/upload_update_reports" => "admin/reports#upload_update_reports" , via: [:post,:get]

  resources :reports, only: [:show,:index]  do
    collection do
       match 'search' => 'reports#search', :via => [:get, :post], :as => :search
       get :get_all_reports
       get 'currency_section'
       post :show_advanced_search
    end 
    get :reset_filterrific, on: :collection    
  end 
  match "/reports/:id/:slug", :to => "reports#show", :via => ["get"]

  resources :categories, only: [:show,:index]

  resources :regions, only: [:show,:index] do
    member do
      match "/country_wise/:country_id", :to => "regions#country_wise", :via => ["get"]
    end
    collection do
      get 'reset_filter'
    end
  end
  resources :publishers, only: [:show,:index] do 
    collection do
      get 'load_more_publisher'
    end
  end
  resources :messages, only: [:create]
  resource :shopping_cart, only: [:show,:create]
  resources :pages, :only => [:show]
  match "/remove_item" => 'shopping_carts#remove_item', :via => [:get, :post]
  post "reports/enquiry" => "reports#enquiry"
  post "reports/enquiry_link" => "reports#enquiry_link"

  get "/clear_cart" => 'shopping_carts#clear_cart'
  get "/load_add_to_cart" => "shopping_carts#load_add_to_cart"
  get "/load_place_order_items" => "shopping_carts#load_place_order_items"

  post "/add_to_cart" => "shopping_carts#add_to_cart"
  

  post "blogs/post_comment" => "blogs#post_comment"

  get "/manage_address"  => 'shopping_carts#manage_address'
  get "/checkout"  => 'shopping_carts#checkout'
  get "/place_order"=> 'shopping_carts#place_order'
  get "/paypal_order_cancel"=> 'shopping_carts#paypal_order_cancel'
  get "/buynow_paypal_cancel"=> 'shopping_carts#buynow_paypal_cancel'
  resources :customers
  match "/update_quantity" => "shopping_carts#update_quantity", via: "post"
  match "/update_user" => "users#update_user", via: "post"
  match "/change_password" => "users#change_password", :via => [:get, :post]
  match "/update_password" => "users#update_password", :via => [:get, :post]
  match "/create_user" => "shopping_carts#create_user", via: "post"
  match "/signin_user" => "shopping_carts#signin_user", via: "post"
  match "/create_customer" => "shopping_carts#create_customer", via: "post"
  match "/complete_order" => "orders#complete_order", via: "post"
  match "/complete_ccavenue_order" => "orders#complete_ccavenue_order", :via => [:get, :post]

  match "/ccavenue_transfer" => "orders#ccavenue_transfer" , via: "post"
  match "/new_user_ccavenue_transfer" => "orders#new_user_ccavenue_transfer" , via: "post"
  
  match "/buynow_ccavenue_transfer" => "orders#buynow_ccavenue_transfer" , via: "post"

  get "purchase_complete" => "orders#purchase_complete"
  get "purchase_cancel" => "orders#purchase_cancel"
  
  get "checkout_complete" => "orders#checkout_complete"
  
  match "/express_checkout" => "orders#express_checkout", via: "post"

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # before_action :check_show_by_id, only: [:show]
  require 'RMagick'
  include Magick
  include ActionView::Helpers::TextHelper
  def index
    @reports = Report.search_report(params[:q],params[:page])
  end

  def search
    fields = if (params["term"].present? && params["publisher"].present?)
               "@(title,publisher_name) '#{params['term']}','#{params['publisher']}'"
             elsif (params["term"].present? && params["publisher"].blank?)
               "@(title) '#{params['term']}'"
             elsif (params["term"].blank? && params["publisher"].present?)
               "@(publisher_name) '#{params['publisher']}'"
             else
               nil
             end

    filter = {
              :order => "#{params[:sorted_by]}", 
              :page => (request.format.symbol == :js) ? nil : params[:page], 
              :limit => 10
             }

    filter[:with] = {:one_user => eval(params[:price])} if params[:price].present?
    @reports = Report.search(fields,filter)
    #get_all_categories(nil,nil,nil,nil,nil)
    
    respond_to do |format|
      format.html {
        @categories = Category.get_all_categories
        render :template => "reports/index"
      }
      format.js { render(partial: 'reports/list') }
    end
  end


  def show
    
    if params[:id].is_number?
      @report = Report.find(params[:id])
    else
      reports = Report.search("@(slug,old_slug) '^#{Riddle::Query.escape(params[:id])}' | ('^#{Riddle::Query.escape(params[:id])}' | '^#{Riddle::Query.escape(params[:id])}*')",:limit => 5)
      reports.each do |report|
        @report = report if (report.slug == params[:id] || report.old_slug == params[:id])
      end
      @report = reports.first unless @report  
    end  

    @enquiry = Enquiry.new
    
    @related_report = Report.related_report(@report.category_id)
    @rates = @report.rates

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @report.to_json }
    end
  end

 def enquiry
    @enquiry = Enquiry.new(enquiry_params)
    if @enquiry.save
      report = Report.find(@enquiry.report_id)
      enquiry_attributes = @enquiry.attributes.select do |attr, value|
        Enquiry.column_names.include?(attr.to_s)
      end
      report_attributes = report.attributes.select do |attr, value|
        Report.column_names.include?(attr.to_s)
      end
      json_data = enquiry_attributes.merge(report_attributes).merge(:enquiry_country_id => @enquiry.country_id, :report_publisher => Report.publisher_name_image_hash[report.publisher_id][:name], :report_category => report.category.name).to_json
      begin
        uri = URI.parse("http://crm.wiseguyreports.com/")
        http = Net::HTTP.new(uri.host, uri.port)
        request = Net::HTTP::Post.new("/CRM/v1/CreateLead")
        request.add_field('Content-Type', 'application/json')
        request.body = json_data
        response = http.request(request)
      rescue
        puts "Error communicating with crm..."
      end
      
      success = "Thank you, Your enquiry has been send"

      #UserMailer.delay(run_at: Time.now).send_enquiry(report, @enquiry)
      UserMailer.send_enquiry(report, @enquiry).deliver
      render :json => {notice: success} 
    else

      render :json => {error: "Please enter an correct capcha"} 

    end
  end

  def advance_search
    @regions = Region.all_regions
    @all_countries = Country.all
    @publishers = Publisher.publisher_list
    @categories = Category.get_all_categories
  end

  def show_advanced_search
    @reports  = Report.advanced_search_reports(params)
  end

  def email_report
    #UserMailer.delay(run_at: Time.now).email_reports(params[:email_report])
   # UserMailer.delay(run_at: Time.now).email_report_to_team(params[:email_report])
    UserMailer.email_reports(params[:email_report]).deliver
    UserMailer.email_report_to_team(params[:email_report]).deliver
    notice = "Thank you, Your message has been sent"
    render :json => {notice: notice}
    
  end

  def sample_request
    @enquiry = Enquiry.new
    reports = Report.search("@(slug,old_slug) '^#{Riddle::Query.escape(params[:id])}' | ('^#{Riddle::Query.escape(params[:id])}' | '^#{Riddle::Query.escape(params[:id])}*')",:limit => 5)
    reports.each do |report|
      @report = report if (report.slug == params[:id] || report.old_slug == params[:id])
    end
    @report = reports.first unless @report
    @countries = Country.get_all_countries
  end

  def check_discount
    @enquiry = Enquiry.new
    reports = Report.search("@(slug,old_slug) '^#{Riddle::Query.escape(params[:id])}' | ('^#{Riddle::Query.escape(params[:id])}' | '^#{Riddle::Query.escape(params[:id])}*')",:limit => 5)
    reports.each do |report|
      @report = report if (report.slug == params[:id] || report.old_slug == params[:id])
    end
    @report = reports.first unless @report
    @countries = Country.get_all_countries
  end

  def any_question
    @enquiry = Enquiry.new
    reports = Report.search("@(slug,old_slug) '^#{Riddle::Query.escape(params[:id])}' | ('^#{Riddle::Query.escape(params[:id])}' | '^#{Riddle::Query.escape(params[:id])}*')",:limit => 5)
    reports.each do |report|
      @report = report if (report.slug == params[:id] || report.old_slug == params[:id])
    end
    @report = reports.first unless @report
    @countries = Country.get_all_countries
  end
  
  def subscriber
    subscriber = Subscriber.search("@(email) #{Riddle::Query.escape(params[:subscriber][:email])}")
    if subscriber.blank?
      Subscriber.create(email: params[:subscriber][:email], status: true)
      UserMailer.new_subscription_to_team(params[:subscriber][:email]).deliver
      flash[:success] = "Thank you for subscribing to Wiseguy Reports Newsletter. We are delighted to have you !! "
      redirect_to root_path
    elsif subscriber.first.status
      flash[:success] = "You are aleady subscribed to Wiseguy Reports Newsletter."
      redirect_to root_path
    else
      subscriber.first.update_attributes(status: true)
      UserMailer.new_subscription_to_team(params[:subscriber][:email]).deliver
      flash[:success] = "Thank you for subscribing to Wiseguy Reports Newsletter. We are delighted to have you !! "
      redirect_to root_path
    end
  end

  def rebuild_cache
    User.build_cache
    Report.clear_fragment_cache

    `rake cache_builder:create_fragment_cache`
    render :nothing => true
  end

  def order_form

    @report = Report.find(params[:report_id])
    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        render :pdf => "order_form", encoding: 'utf8'
      end
    end
  end

  def report_info
    @report = Report.find(params[:report_id])

    respond_to do |format|
      format.html do
        render :layout => false
      end
      format.pdf do
        render :pdf => "report_info", encoding: 'utf8'
      end
    end
  end
  

  private

  def subscriber_params
    params.require(:subscriber).permit(:email,:status)
  end

  def enquiry_params
    params.require(:enquiry).permit(:first_name,:last_name,:email,:job_title, :phone_no, :company, :interest_area, :enquiry, :message,:enquiry_type,:report_id,:country_id)
  end

  def check_show_by_id
    if params[:id].is_number?
      redirect_to :action => :show,:id => Report.find(params[:id]).slug
    end
  end
end

app/views/reports/_capcha.html.erb
      <div class="form-group">
        <label for="capcha" class="col-sm-3 control-label"></label>
        <div class="col-sm-9">
                <%= recaptcha_tags :display => { :theme => "white" }%>
        </div>
      </div>

app/views/reports/_currency_section.html.erb
            
                                     <%= form_for "currency", :url => shopping_cart_path(:report_id => @report), :method => 'post' , :html => {:class=>"form-horizontal",:id=>"update_currency"} do |f| %>    
                   
                                         <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab1" data-toggle="tab">USD <i class="fa fa-usd"></i></a></li>
                     <li><a href="#tab2" data-toggle="tab">GBP <i class="fa fa-gbp"></i></a></li>
                    <li><a href="#tab3" data-toggle="tab">Euro <i class="fa fa-eur"></i></a></li>
                   
                    <li><a href="#tab4" data-toggle="tab">Yen <i class="fa fa-jpy"></i></a></li>
          <li><a href="#tab5" data-toggle="tab">INR <i class="fa fa-inr"></i></a></li>
               
                </ul>
                <div class="tab-content" style="margin-bottom:0px;padding: 10px;">
                   <div class="tab-pane fade in active" id="tab1">
                       <p>  
                        <%if @report.one_user.present?%><%= radio_button_tag 'currency', "one_user-USD",:checked=>"true" %>1-user PDF<span style="float:right"> <%= number_to_currency @report.one_user%></span><br/><%end%>
                       <%if @report.five_user.present?%><%= radio_button_tag 'currency', "five_user-USD"%>1-5 User PDF <span style="float:right"><%= number_to_currency @report.five_user%></span><br/><%end%>
                       <%if @report.site_user.present?%><%= radio_button_tag 'currency', "site_user-USD"%> Site PDF <span style="float:right;"><%= number_to_currency @report.site_user%></span><br/><%end%>
                       <%if @report.enterprise_user.present?%><%= radio_button_tag 'currency', "enterprise_user-USD" %> Enterprise PDF <span style="float:right"><%= number_to_currency @report.enterprise_user%>
                      </span><%end%></p>
                    </div>
                    <div class="tab-pane fade" id="tab2">

                       <p>   
                       <%if @report.one_user.present?%><%= radio_button_tag 'currency', "one_user-GBP" %>1-user PDF<span style="float:right"> <i class="fa fa-gbp"></i><%= number_with_precision(@gbp, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.five_user.present?%><%= radio_button_tag 'currency', "five_user-GBP"%>1-5 User PDF <span style="float:right"> <i class="fa fa-gbp"></i><%= number_with_precision(@gbp_five, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.site_user.present?%><%= radio_button_tag 'currency', "site_user-GBP"%> Site PDF <span style="float:right;"> <i class="fa fa-gbp"></i><%= number_with_precision(@gbp_site, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.enterprise_user.present?%><%= radio_button_tag 'currency', "enterprise_user-GBP" %> Enterprise PDF <span style="float:right"> <i class="fa fa-gbp"></i><%= number_with_precision(@gbp_enterprise, :precision => 2, :delimiter => ',') %>
                      </span><%end%>
                      </p>
                    </div>
                    <div class="tab-pane fade" id="tab3">
                      <p>   
                       <%if @report.one_user.present?%><%= radio_button_tag 'currency', "one_user-EUR" %>1-user PDF<span style="float:right"> <i class="fa fa-eur"></i><%= number_with_precision(@eur, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.five_user.present?%><%= radio_button_tag 'currency', "five_user-EUR"%>1-5 User PDF <span style="float:right"> <i class="fa fa-eur"></i><%= number_with_precision(@eur_five, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.site_user.present?%><%= radio_button_tag 'currency', "site_user-EUR"%> Site PDF <span style="float:right;"> <i class="fa fa-eur"></i><%= number_with_precision(@eur_site, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.enterprise_user.present?%><%= radio_button_tag 'currency', "enterprise_user-EUR" %> Enterprise PDF <span style="float:right"> <i class="fa fa-eur"></i><%= number_with_precision(@eur_enterprise, :precision => 2, :delimiter => ',') %>
                      </span><%end%>
                      </p>

                    </div>
                 
                    <div class="tab-pane fade" id="tab4">
                      <p>   
                       <%if @report.one_user.present?%><%= radio_button_tag 'currency', "one_user-JPY" %>1-user PDF<span style="float:right"> <i class="fa fa-jpy"></i><%= number_with_precision(@jpy, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.five_user.present?%><%= radio_button_tag 'currency', "five_user-JPY"%>1-5 User PDF <span style="float:right"> <i class="fa fa-jpy"></i><%= number_with_precision(@jpy_five, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.site_user.present?%><%= radio_button_tag 'currency', "site_user-JPY"%> Site PDF <span style="float:right;"> <i class="fa fa-jpy"></i><%= number_with_precision(@jpy_site, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.enterprise_user.present?%><%= radio_button_tag 'currency', "enterprise_user-JPY" %> Enterprise PDF <span style="float:right"> <i class="fa fa-jpy"></i><%= number_with_precision(@jpy_enterprise, :precision => 2, :delimiter => ',') %>
                      </span><%end%>
                      </p>


                    </div>
                               <div class="tab-pane fade" id="tab5">
                      <p>   
                       <%if @report.one_user.present?%><%= radio_button_tag 'currency', "one_user-INR" %>1-user PDF<span style="float:right"> <i class="fa fa-inr"></i><%= number_with_precision(@inr, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.five_user.present?%><%= radio_button_tag 'currency', "five_user-INR"%>1-5 User PDF <span style="float:right"> <i class="fa fa-inr"></i><%= number_with_precision(@inr_five, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.site_user.present?%><%= radio_button_tag 'currency', "site_user-INR"%> Site PDF <span style="float:right;"> <i class="fa fa-inr"></i><%= number_with_precision(@inr_site, :precision => 2, :delimiter => ',') %></span><br/><%end%>
                       <%if @report.enterprise_user.present?%><%= radio_button_tag 'currency', "enterprise_user-INR" %> Enterprise PDF <span style="float:right"> <i class="fa fa-inr"></i><%= number_with_precision(@inr_enterprise, :precision => 2, :delimiter => ',') %>
                      </span><%end%>
                      </p>


                    </div>
                     <%if @report.upcoming?%>

  <input type="image" src="/assets/prebooknow.png" alt="Submit" style="float:right;height:35px">
        <%else%>
                 <img src="/assets/godaddyseal.gif" alt="Logo" class="img-responsive" style="float:left;padding-top:20px">
                             <button type="submit" id="send" class="btn btn-primary btn-sm" style="float:right"><i class="fa fa-shopping-cart"></i>Add to cart</button> 
        <%end%>

                      <%end%>    

                </div>

                        <img src="/assets/cc.jpg" alt="Logo" class="img-responsive" style="padding: 15px 15px 0px 20px;">

app/views/reports/_report.html.erb
 <div class="record" data-id="<%= report.id %>">
                <div class="panel panel-info">

              <div class="panel-body panelbodyfont" >
                <%if report.report_image?%>
                  <%= image_tag report.report_image_url(:thumb), :class=>"img-thumbnail panelbodyimg"  %> 
                <%elsif Report.category_name_image_hash[report.category_id][:logo].present?%>
                   <img src="<%=Report.category_name_image_hash[report.category_id][:logo]%>" alt="<%=Report.category_name_image_hash[report.category_id][:name] %>" class="img-thumbnail panelbodyimg">
                <%else%>
                  <%= image_tag report.publisher.report_image_url(:thumb), :class=>"img-thumbnail panelbodyimg" %> 

                  
                <%end%>
                <span> <a href="/reports/<%= report.slug%>" class="fontcolor"><b><%=  report.title %></b><br/><br/>
                  <%if report.upcoming%>
                    <b class="datecolor">Due Date: </b><%if report.publish_month?%><%= report.publish_month.to_date.strftime("%B, %Y") %><%else%>Coming Soon<%end%><br/>
                  <%else%>
                <b class="datecolor">Published: </b><%= report.day rescue nil%> <%= report.publish_month.to_date.strftime("%B, %Y") rescue nil%><br/>
                        <%end%>       
               

              </a></span>

              </div>
            </div>  </div>

app/views/reports/continent.html.erb
    <section class="breadcrumb-wrapper">
        <div class="container">
  
  <%= render "shared/search_form"%>
           
        </div>
    </section>






<section class="content " id="eshop">
	<div class="container ">



		
		<div class="col-sm-12">
		<!-- <ul> -->
		  <%# @grouped.keys.sort.each do |letter| -%>
		   <div class="col-md-12">
		  <br/><br/>
		   <!--   <h5><strong><%#= letter %></strong></h5> -->

		      <ul>
		        <% @continents.each_slice(4) do |tag_array| -%>
			        <% tag_array.each do |continent| %>
			          <div class="col-md-3" style="padding-bottom:30px"><a href="/report_list?continent_id=<%=continent.id%>"><img src="assets/<%= continent.id%>.gif" height="50" width="50">&nbsp;&nbsp; <%= continent.name%> (<%=continent.reports.count%>)</a></div>
			     
			        <% end -%><br/>
		         <% end %>
		      </ul>
		    </div>
		
		</ul>
	</div>
	</div>
</section>

app/views/reports/currency_section.js.erb
<%= render(:partial => "currency_section" ) %>